cdn: https://files.vxk.cz/omstredni/
cdnapi: http://mutabor.vxk.cz/cdn
apps:
  - module: ./index.js
    url: https://dev.modurad.otevrenamesta.cz/omstredni/mediaman
    uploadurl: https://upload.vxk.cz/
    storageurl: https://files.vxk.cz

user:
  username: vencax
  password: heslo